import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { SOURCE_ID, toObservation, toObservations } from "../ingestion/agendalx/observation-adapter.mjs";

const FIXTURE_PATH = new URL("../fixtures/agendalx/music-sample.json", import.meta.url);

async function loadFixture() {
  return JSON.parse(await readFile(FIXTURE_PATH, "utf8"));
}

test("all 10 retained AgendaLX music records convert successfully", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  assert.equal(observations.length, 10);
  assert.equal(fixture.records.length, 10);
});

test("every AgendaLX Observation carries the canonical source_id and a non-empty source_record_id", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  for (const observation of observations) {
    assert.equal(observation.source_id, SOURCE_ID);
    assert.equal(observation.source_id, "agendalx");
    assert.equal(typeof observation.source_record_id, "string");
    assert.ok(observation.source_record_id.length > 0);
  }
});

test("source_record_id matches the source's own record id", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  assert.deepEqual(
    observations.map((o) => o.source_record_id),
    fixture.records.map((r) => String(r.id)),
  );
});

test("retrieved_at comes from the fixture's retained provenance, not the current time", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  for (const observation of observations) {
    assert.equal(observation.retrieved_at, fixture.metadata.retrieved_at);
  }
  // Sanity: this is a fixed, already-retained timestamp, not something
  // freshly generated by running the test.
  assert.equal(fixture.metadata.retrieved_at, "2026-08-23T15:56:34.0855101Z");
});

test("title, event_url, and venue_name map from genuinely observed fields", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  const fadoNaRua = observations.find((o) => o.source_record_id === "241259");
  assert.equal(fadoNaRua.title, "Fado na Rua");
  assert.equal(fadoNaRua.event_url, "https://www.agendalx.pt/events/event/fado-na-rua-2/");
  assert.equal(fadoNaRua.venue_name, "Junta de Freguesia de Santa Maria Maior");
});

test("start preserves the source's raw date text and a DATE_ONLY parsed date; no time is guessed", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  const meoKalorama = observations.find((o) => o.source_record_id === "230515");
  assert.equal(meoKalorama.start.date, "2026-08-28");
  assert.equal(meoKalorama.start.certainty, "DATE_ONLY");
  assert.equal(meoKalorama.start.iso, null, "no UTC instant should be fabricated from date-only source data");
  assert.ok(meoKalorama.start.raw.includes("28 agosto a 30 agosto 2026"));
});

test("end is left empty: LastDate is a recurring-schedule end, not a single event's end time", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  for (const observation of observations) {
    assert.equal(observation.end.iso, null);
    assert.equal(observation.end.date, null);
    assert.equal(observation.end.certainty, "UNKNOWN");
  }
});

test("free events get a derived price_text of 'Free'; PHP-serialized price_val is never guessed at", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);

  const sunsetSessions = observations.find((o) => o.source_record_id === "240378");
  assert.equal(sunsetSessions.price_text, "Free");

  const hasJazz = observations.find((o) => o.source_record_id === "241429");
  assert.equal(hasJazz.price_text, null, "price_val is PHP-serialized; must not be silently decoded/guessed");
  assert.equal(
    hasJazz.source_fields.price_val,
    fixture.records.find((r) => r.id === 241429).price_val,
    "raw price_val must still be preserved verbatim in source_fields",
  );
});

test("no coordinates, address, artist, or canonical Venue/Event identity are invented", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  for (const observation of observations) {
    assert.equal(observation.location_text, null);
    const keys = Object.keys(observation);
    for (const forbidden of [
      "latitude",
      "longitude",
      "coordinates",
      "artist",
      "artist_id",
      "canonical_venue_id",
      "event_id",
      "canonical_event_id",
    ]) {
      assert.equal(keys.includes(forbidden), false, forbidden);
    }
  }
});

test("raw_evidence honestly records that the retained fixture is parsed/reserialized JSON, not byte-identical", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  for (const observation of observations) {
    assert.equal(observation.raw_evidence.fixture_path, "fixtures/agendalx/music-sample.json");
    assert.equal(observation.raw_evidence.evidence_kind, "PARSED_STRUCTURED_JSON");
    assert.equal(
      observation.raw_evidence.byte_faithful,
      false,
      "fixtures/agendalx/music-sample.json is written via JSON.stringify of parsed records, not a retained raw HTTP body",
    );
  }
});

test("Observation generation is deterministic from the fixture", async () => {
  const fixture = await loadFixture();
  assert.deepEqual(toObservations(fixture), toObservations(fixture));
});

test("null/absent fields (e.g. subtitle-derived facts not in the contract) never appear as fabricated top-level values", async () => {
  const fixture = await loadFixture();
  const observations = toObservations(fixture);
  for (const observation of observations) {
    assert.equal(typeof observation.description === "string" || observation.description === null, true);
  }
});

test("toObservation on a single record matches the corresponding entry from toObservations", async () => {
  const fixture = await loadFixture();
  const [record] = fixture.records;
  const single = toObservation(record, {
    retrievedAt: fixture.metadata.retrieved_at,
    sourceUrl: fixture.metadata.request_url,
    contentType: undefined,
    fixturePath: "fixtures/agendalx/music-sample.json",
  });
  const [fromBatch] = toObservations(fixture);
  assert.deepEqual(single, fromBatch);
});
