"use client";

import { useEffect, useMemo, useState } from "react";
import { DiscoveryMap, type MapMarker, type SearchCountry } from "@/components/DiscoveryMap";
import { getMarkersForCountry } from "@/ingestion/map/projection.mjs";
import { resolveMapData } from "@/ingestion/map/runtime-publication.mjs";
import {
  filterMarkersByArtistId,
  filterMarkersByGenre,
  findArtistByExactName,
  searchArtists,
} from "@/ingestion/map/artist-genre-search.mjs";
import publicationData from "@/data/public/lisbon-porto-map.json";

// Mirrors the publication artifact's own top-level `artists` search index
// (ingestion/map/publication.mjs's buildArtistIndex()) — not the full
// enriched Artist record, just enough for the search field below.
type ArtistIndexEntry = {
  artist_id: string;
  canonical_name: string;
  aliases: string[];
};

// data/public/lisbon-porto-map.json is the committed, BUNDLED-AT-BUILD-TIME
// fallback PRODUCT PUBLICATION ARTIFACT (BOTM-PUBLIC-MAP-LIVE-DATA-01) —
// generated by `npm run publish:map-data`/`npm run unattended` from the
// real, live Lisbon+Porto ingestion/display pipeline
// (ingestion/lisbon-porto/run.mjs + ingestion/map/publication.mjs), never
// hand-edited. See docs/PUBLIC_MAP_LIVE_DATA_01.md.
//
// BOTM-RUNTIME-PUBLICATION-BRIDGE-01: when
// NEXT_PUBLIC_BOTM_MAP_DATA_URL is configured, this page ALSO tries that
// runtime endpoint (ingestion/publication-server/run.mjs) client-side,
// AFTER the page has already been built/deployed — a fresh
// twice-daily-collected dataset can reach real visitors without a new Git
// commit or Netlify rebuild for every collection cycle. If that endpoint
// is unset, unreachable, slow, or returns anything that doesn't validate
// as a genuine publication artifact, this page keeps rendering the
// bundled dataset above — the map is never left blank because a runtime
// service happens to be temporarily down. See
// ingestion/map/runtime-publication.mjs and docs/RUNTIME_PUBLICATION_BRIDGE.md.
//
// The public homepage does not scrape venue websites. It renders the
// latest successfully published map dataset, runtime or bundled.
const BUNDLED_ARTIFACT = publicationData;
const RUNTIME_MAP_DATA_URL = process.env.NEXT_PUBLIC_BOTM_MAP_DATA_URL || null;

const genres = ["Any", "Rock", "Indie", "Alternative", "Electronic", "Jazz", "Folk", "Pop", "Metal"];
const quickDates = ["Tonight", "This weekend", "Next 7 days", "This month"];

function PinIcon() {
  return (
    <svg aria-hidden="true" viewBox="0 0 24 24" className="field-icon">
      <path d="M12 21s7-5.4 7-12a7 7 0 1 0-14 0c0 6.6 7 12 7 12Z" />
      <circle cx="12" cy="9" r="2.3" />
    </svg>
  );
}

function CalendarIcon() {
  return (
    <svg aria-hidden="true" viewBox="0 0 24 24" className="field-icon">
      <rect x="3.5" y="5" width="17" height="16" rx="2" />
      <path d="M7.5 3.5v3M16.5 3.5v3M3.5 9.5h17" />
    </svg>
  );
}

function MusicIcon() {
  return (
    <svg aria-hidden="true" viewBox="0 0 24 24" className="field-icon">
      <path d="M9 18V5l11-2v13" />
      <circle cx="6" cy="18" r="3" />
      <circle cx="17" cy="16" r="3" />
    </svg>
  );
}

function TicketIcon() {
  return (
    <svg aria-hidden="true" viewBox="0 0 24 24" className="field-icon">
      <path d="M4 6.5A2.5 2.5 0 0 1 6.5 4h11A2.5 2.5 0 0 1 20 6.5v2a2.5 2.5 0 0 0 0 5v2a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 4 15.5v-2a2.5 2.5 0 0 0 0-5v-2Z" />
      <path d="M12 7v2M12 11v2M12 15v2" />
    </svg>
  );
}

function ArrowIcon() {
  return (
    <svg aria-hidden="true" viewBox="0 0 24 24" className="arrow-icon">
      <path d="M5 12h13M13 6l6 6-6 6" />
    </svg>
  );
}

export default function Home() {
  const [view, setView] = useState<"map" | "list">("map");
  const [country, setCountry] = useState<SearchCountry>("Portugal");
  // Starts as the bundled artifact (correct for the initial server-rendered
  // HTML and for a visitor whose browser never gets a chance to run the
  // runtime fetch below) and is only ever REPLACED, never cleared, if a
  // validated runtime response arrives later. `dataSource` is an honest,
  // internal indicator of which one is actually being rendered right now —
  // no visible UI redesign required, but available for a future debug
  // surface or for tests.
  const [publicationArtifact, setPublicationArtifact] = useState(BUNDLED_ARTIFACT);
  const [dataSource, setDataSource] = useState<"runtime" | "bundled">("bundled");
  // BEATMAPPED-ENRICHMENT-PILOT-01 — "Any" matches filterMarkersByGenre's
  // own no-op convention; selectedArtistId is only ever set from an exact
  // canonical_name match (see the Artist field's onChange below) — never
  // a fuzzy guess, matching this pilot's conservative identity rule.
  const [selectedGenre, setSelectedGenre] = useState("Any");
  const [artistQuery, setArtistQuery] = useState("");
  const [selectedArtistId, setSelectedArtistId] = useState<string | null>(null);

  useEffect(() => {
    if (!RUNTIME_MAP_DATA_URL) return; // unset -> bundled fallback only, no network call at all
    let cancelled = false;
    resolveMapData({ runtimeUrl: RUNTIME_MAP_DATA_URL, bundledArtifact: BUNDLED_ARTIFACT }).then((result) => {
      if (cancelled) return;
      setPublicationArtifact(result.artifact);
      setDataSource(result.source);
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const portugalMarkers = useMemo(
    () => (publicationArtifact.countries.Portugal.markers as MapMarker[]) ?? [],
    [publicationArtifact],
  );
  const visibleMarkers = useMemo(
    () => getMarkersForCountry(country, portugalMarkers) as MapMarker[],
    [country, portugalMarkers],
  );

  // BEATMAPPED-ENRICHMENT-PILOT-01 — the publication artifact's own
  // Artist search index (ingestion/map/publication.mjs's
  // buildArtistIndex()); empty for a pre-pilot/runtime artifact that
  // hasn't been re-published with artist enrichment yet.
  const artistIndex = useMemo(
    () => (publicationArtifact.artists as ArtistIndexEntry[]) ?? [],
    [publicationArtifact],
  );

  // Genre and Artist each independently narrow visibleMarkers down to
  // matching display listings only (ingestion/map/artist-genre-search.mjs)
  // — the mapped object stays the Event throughout; selecting an Artist
  // never turns the Artist itself into a pin.
  const filteredMarkers = useMemo(() => {
    const byGenre = filterMarkersByGenre(visibleMarkers, selectedGenre) as MapMarker[];
    return filterMarkersByArtistId(byGenre, selectedArtistId) as MapMarker[];
  }, [visibleMarkers, selectedGenre, selectedArtistId]);

  const listingCount = useMemo(
    () => filteredMarkers.reduce((sum, marker) => sum + (marker.display_listings?.length ?? marker.listings?.length ?? 0), 0),
    [filteredMarkers],
  );

  // Narrows the Artist datalist's own suggestions as the visitor types —
  // separate from selectedArtistId (which only an exact match sets, see
  // handleArtistQueryChange below).
  const artistSuggestions = useMemo(
    () => searchArtists(artistQuery, artistIndex) as ArtistIndexEntry[],
    [artistQuery, artistIndex],
  );

  function handleArtistQueryChange(value: string) {
    setArtistQuery(value);
    if (value.trim() === "") {
      setSelectedArtistId(null);
      return;
    }
    // Only an EXACT canonical_name match (e.g. picked from the datalist)
    // narrows the map — matching this pilot's conservative identity rule
    // (similar names alone are never enough), never a partial-substring
    // guess while the visitor is still mid-typing.
    const exact = findArtistByExactName(value, artistIndex);
    setSelectedArtistId(exact ? exact.artist_id : null);
  }

  return (
    <main className="site-shell" data-map-data-source={dataSource}>
      <div className="page-wrap">
        <header className="site-header">
          <a href="#top" className="brand" aria-label="Band on the Map home">
            <span className="brand-mark" aria-hidden="true">♪</span>
            <span>Band on the Map</span>
          </a>
          <nav className="header-nav" aria-label="Primary navigation">
            <a href="#discover">Discover</a>
            <a href="#about">About</a>
          </nav>
        </header>

        <section className="hero" id="top">
          <div className="hero-copy">
            <p className="eyebrow">Music, mapped around you</p>
            <h1>Where will the <em>sound</em> take you?</h1>
            <p className="hero-description">Choose a destination and dates, then discover the live music waiting there.</p>
          </div>
          <div className="hero-note" aria-hidden="true">
            <span>Portugal</span>
            <span>Croatia</span>
          </div>
        </section>

        <section className="search-panel" aria-labelledby="search-heading">
          <div className="search-heading">
            <p className="eyebrow">Start exploring</p>
            <h2 id="search-heading">Find your next live moment</h2>
          </div>
          <form className="search-form" onSubmit={(event) => event.preventDefault()}>
            <label className="field field-where">
              <span className="field-label">Where</span>
              <span className="field-control">
                <PinIcon />
                <select
                  value={country}
                  aria-label="Where"
                  onChange={(event) =>
                    setCountry(event.target.value as SearchCountry)
                  }
                >
                  <option>Portugal</option>
                  <option>Croatia</option>
                </select>
              </span>
            </label>
            <label className="field">
              <span className="field-label">From</span>
              <span className="field-control">
                <CalendarIcon />
                <input type="date" aria-label="From date" />
              </span>
            </label>
            <label className="field">
              <span className="field-label">To</span>
              <span className="field-control">
                <CalendarIcon />
                <input type="date" aria-label="To date" />
              </span>
            </label>
            <label className="field">
              <span className="field-label">Type</span>
              <span className="field-control">
                <MusicIcon />
                <select defaultValue="All" aria-label="Event type">
                  <option>All</option>
                  <option>Gigs</option>
                  <option>Festivals</option>
                </select>
              </span>
            </label>
            <label className="field">
              <span className="field-label">Genre</span>
              <span className="field-control">
                <MusicIcon />
                <select
                  value={selectedGenre}
                  aria-label="Genre"
                  onChange={(event) => setSelectedGenre(event.target.value)}
                >
                  {genres.map((genre) => <option key={genre}>{genre}</option>)}
                </select>
              </span>
            </label>
            <label className="field">
              <span className="field-label">Artist</span>
              <span className="field-control">
                <MusicIcon />
                <input
                  type="text"
                  list="artist-search-options"
                  aria-label="Artist"
                  placeholder="Any artist"
                  value={artistQuery}
                  onChange={(event) => handleArtistQueryChange(event.target.value)}
                />
                <datalist id="artist-search-options">
                  {artistSuggestions.map((artist) => (
                    <option key={artist.artist_id} value={artist.canonical_name} />
                  ))}
                </datalist>
              </span>
            </label>
            <label className="field">
              <span className="field-label">Price</span>
              <span className="field-control">
                <TicketIcon />
                <select defaultValue="Any" aria-label="Price">
                  <option>Any</option>
                  <option>Free</option>
                  <option>Under €20</option>
                  <option>Under €50</option>
                </select>
              </span>
            </label>
            <button className="primary-button" type="submit">
              Explore music <ArrowIcon />
            </button>
          </form>
          <div className="quick-dates" aria-label="Quick date options">
            <span className="quick-label">Quick dates</span>
            {quickDates.map((date) => <button type="button" key={date}>{date}</button>)}
          </div>
        </section>

        <section className="discovery" id="discover" aria-labelledby="discovery-heading">
          <div className="section-heading">
            <div>
              <p className="eyebrow">Your discovery space</p>
              <h2 id="discovery-heading">Explore the map</h2>
            </div>
            <div className="view-toggle" role="group" aria-label="Discovery view">
              <button type="button" className={view === "map" ? "active" : ""} onClick={() => setView("map")}>Map</button>
              <button type="button" className={view === "list" ? "active" : ""} onClick={() => setView("list")}>List</button>
            </div>
          </div>
          <div className={`map-placeholder ${view === "list" ? "list-mode" : ""}`}>
            <DiscoveryMap country={country} markers={filteredMarkers} />
            <div className={`map-status ${filteredMarkers.length > 0 ? "" : "is-empty"}`} aria-live="polite">
              {filteredMarkers.length > 0 ? (
                <>
                  <p className="empty-kicker">Live music in {country}</p>
                  <p>
                    {listingCount} real source listing{listingCount === 1 ? "" : "s"} across{" "}
                    {filteredMarkers.length} venue{filteredMarkers.length === 1 ? "" : "s"}
                  </p>
                </>
              ) : (
                <>
                  <p className="empty-kicker">{country}</p>
                  <p>
                    {selectedArtistId || selectedGenre !== "Any"
                      ? "No listings match this search yet — try a different artist or genre."
                      : `No listings here yet — we're still gathering source data for ${country}.`}
                  </p>
                </>
              )}
            </div>
            <div className="map-caption">A quieter way to find your next night out</div>
          </div>
        </section>

        <footer className="site-footer" id="about">
          <span>Band on the Map</span>
          <span>Live music, wherever you are.</span>
        </footer>
      </div>
    </main>
  );
}
