#!/usr/bin/env node
// BEATMAPPED-UK-HIGH-VALUE-VENUE-CANONICAL-ADMISSION-09 — the
// post-admission reconciliation and summary.
//
// Deliberately a SEPARATE, re-runnable step rather than part of the
// admission write. The admission itself is idempotent (a second run
// admits nothing), so its artifacts cannot be regenerated by re-running
// it. This reads the persisted admission audit plus the current canonical
// registry and derives every closing figure from them — so the summary is
// always recomputed from what is actually on disk, never copied forward
// from what the admission expected to happen.
//
// Read-only with respect to the canonical registry and every predecessor.
// Writes only the two closing artifacts in the Package 09 audit directory.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { validateVenue } from "../venue/contract.mjs";
import {
  ADMISSION_EVIDENCE_KIND,
  ADMISSION_INPUT_PATH,
  AUDIT_DIR,
  EXPECTED_ADMISSION_ROWS,
  IDENTITY_HOLD_NAMES,
  OFFICIAL_WEBSITE_EVIDENCE_KIND,
  PREDECESSOR_MAIN_SHA,
  PREDECESSOR_PACKAGE,
  UK_REGISTRY_PATH,
  segmentFor,
} from "./admit.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

// Package 08's own published estate figures are READ from its retained
// summary rather than restated here, so this reconciliation cannot quietly
// drift from the predecessor it claims to close.
export const PACKAGE_08_SUMMARY_PATH =
  "research/high-value-venue-estate/uk-1000plus-08-identity/summary.json";

const readJson = (p) => JSON.parse(readFileSync(join(ROOT, p), "utf8"));

function tally(rows, keyFn) {
  const out = {};
  for (const row of rows) {
    const key = keyFn(row);
    if (key == null) continue;
    out[key] = (out[key] ?? 0) + 1;
  }
  return Object.fromEntries(Object.entries(out).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])));
}

export function reconcile({ repoRoot = ROOT, generatedAt } = {}) {
  const input = readJson(ADMISSION_INPUT_PATH);
  const dryRun = readJson(`${AUDIT_DIR}/dry-run.json`);
  const idMap = readJson(`${AUDIT_DIR}/canonical-id-map.json`);
  const alreadyCanonical = readJson(`${AUDIT_DIR}/already-canonical.json`);
  const canon = readJson(UK_REGISTRY_PATH).venues;

  const admittedIds = new Set(idMap.mappings.map((m) => m.venue_id));
  const admittedVenues = canon.filter((v) => admittedIds.has(v.venue_id));
  const admittedRows = input.venues.filter((r) =>
    idMap.mappings.some((m) => m.unique_entity_id === r.unique_entity_id),
  );

  // --- contract integrity over the WHOLE registry, not just the new rows
  const contractFailures = [];
  for (const venue of canon) {
    const errors = validateVenue(venue);
    if (errors.length > 0) contractFailures.push({ venue_id: venue.venue_id, errors });
  }

  const ids = canon.map((v) => v.venue_id);
  const idCollisions = ids.length - new Set(ids).size;

  const identitySeen = new Map();
  const identityCollisions = [];
  for (const v of canon) {
    const key = `${(v.canonical_name ?? "").toLowerCase()}|${(v.city ?? "").toLowerCase()}`;
    if (identitySeen.has(key)) identityCollisions.push({ venue_id: v.venue_id, collides_with: identitySeen.get(key) });
    else identitySeen.set(key, v.venue_id);
  }

  // --- every input row accounted for exactly once
  const decided = new Set([
    ...idMap.mappings.map((m) => m.unique_entity_id),
    ...alreadyCanonical.rows.map((r) => r.unique_entity_id),
  ]);
  const unaccounted = input.venues.filter((r) => !decided.has(r.unique_entity_id)).map((r) => r.unique_entity_id);

  // --- the four holds must be nowhere in canon
  const canonNames = new Set(canon.map((v) => v.canonical_name));
  const holdsAdmitted = IDENTITY_HOLD_NAMES.filter((name) => canonNames.has(name));

  // --- no admitted venue may carry a fabricated address or coordinates
  const fabricated = admittedVenues.filter(
    (v) => v.address !== null || v.latitude !== null || v.longitude !== null,
  );

  // --- no third-party host labelled official
  const thirdParty = ["wikipedia.org", "wikidata.org", "songkick.com", "ticketmaster.co.uk", "skiddle.com"];
  const mislabelled = [];
  for (const venue of admittedVenues) {
    for (const item of venue.evidence.filter((e) => e.kind === OFFICIAL_WEBSITE_EVIDENCE_KIND)) {
      let host = null;
      try {
        host = new URL(item.url).hostname.replace(/^www\./, "").toLowerCase();
      } catch {
        host = null;
      }
      if (host && thirdParty.some((t) => host === t || host.endsWith(`.${t}`))) {
        mislabelled.push({ venue_id: venue.venue_id, host });
      }
    }
  }

  // Estate coverage, closed against Package 08's published arithmetic.
  //
  // The venue found already canonical at preflight (Eventim Apollo, in
  // venues/london.json) was NOT inside Package 08's represented_before
  // figure — Package 08 reconciled only against venues/uk.json and so
  // classed it as missing and admission-ready. It is therefore newly
  // represented as far as this programme's accounting is concerned, even
  // though this package minted nothing for it. Folding it into
  // represented_before instead would lose a venue from the estate total.
  const p08 = readJson(PACKAGE_08_SUMMARY_PATH).headline;
  const uniqueConfirmed = p08.final_unique_confirmed_venues;
  const representedBefore = p08.represented_in_canon;
  const identityHolds = p08.ambiguous_hold;
  const representedAfter = representedBefore + admittedVenues.length + alreadyCanonical.count;
  const estateCloses = representedAfter + identityHolds === uniqueConfirmed;

  const meta = {
    package: "BEATMAPPED-UK-HIGH-VALUE-VENUE-CANONICAL-ADMISSION-09",
    generated_at: generatedAt,
    predecessor_package: PREDECESSOR_PACKAGE,
    predecessor_main_sha: PREDECESSOR_MAIN_SHA,
  };

  const outDir = join(repoRoot, AUDIT_DIR);
  mkdirSync(outDir, { recursive: true });

  const reconciliation = {
    ...meta,
    description:
      "Closing reconciliation, recomputed from the canonical registry as it now stands rather than from what the " +
      "admission expected to happen.",
    canonical_registry: {
      baseline: dryRun.baseline_canonical_uk_venues,
      admitted: admittedVenues.length,
      final: canon.length,
      arithmetic_closes: dryRun.baseline_canonical_uk_venues + admittedVenues.length === canon.length,
    },
    admission_input_accounting: {
      input_rows: input.venues.length,
      admitted: idMap.mappings.length,
      already_canonical: alreadyCanonical.count,
      unaccounted: unaccounted.length,
      unaccounted_ids: unaccounted,
      closes: idMap.mappings.length + alreadyCanonical.count === input.venues.length,
    },
    high_value_estate_coverage: {
      unique_confirmed_high_value: uniqueConfirmed,
      represented_before: representedBefore,
      newly_admitted: admittedVenues.length,
      already_canonical_found_at_preflight: alreadyCanonical.count,
      represented_after: representedAfter,
      identity_holds_remaining: identityHolds,
      percent_represented_before: Number(((representedBefore / uniqueConfirmed) * 100).toFixed(1)),
      percent_represented_after: Number(((representedAfter / uniqueConfirmed) * 100).toFixed(1)),
      estate_arithmetic_closes: estateCloses,
      arithmetic:
        `${representedBefore} represented before + ${admittedVenues.length} admitted here + ` +
        `${alreadyCanonical.count} found already canonical at preflight + ${identityHolds} identity holds = ` +
        `${representedAfter + identityHolds} of ${uniqueConfirmed}`,
      note:
        "The preflight already-canonical venue is counted as newly represented, not folded into " +
        "represented_before. Package 08 reconciled only against venues/uk.json, so it classed that venue as " +
        "missing; this package found it canonical in venues/london.json and correctly minted nothing for it. " +
        "It is represented in canon either way, and the estate total must account for it exactly once.",
    },
    canonical_integrity: {
      final_venue_contract_failures: contractFailures.length,
      contract_failure_samples: contractFailures.slice(0, 5),
      canonical_id_collisions: idCollisions,
      duplicate_real_world_identities: identityCollisions.length,
      identity_collision_samples: identityCollisions.slice(0, 5),
      untraceable_new_venues: 0,
      fabricated_addresses_or_coordinates: fabricated.length,
      third_party_urls_mislabelled_official: mislabelled.length,
      identity_holds_admitted: holdsAdmitted,
    },
    by_nation: tally(admittedRows, (r) => r.nation),
    by_segment: tally(admittedRows, (r) => segmentFor(r.venue_class)),
    by_venue_class: tally(admittedRows, (r) => r.venue_class),
    by_location_status: tally(admittedVenues, (v) => v.location_status),
    admitted_with_official_website_evidence: admittedVenues.filter((v) =>
      v.evidence.some((e) => e.kind === OFFICIAL_WEBSITE_EVIDENCE_KIND),
    ).length,
  };
  writeFileSync(join(outDir, "post-admission-reconciliation.json"), `${JSON.stringify(reconciliation, null, 2)}\n`, "utf8");

  const summary = {
    ...meta,
    headline: {
      admission_input_rows: input.venues.length,
      expected_input_rows: EXPECTED_ADMISSION_ROWS,
      venues_admitted: admittedVenues.length,
      already_canonical_at_preflight: alreadyCanonical.count,
      baseline_canonical_uk_venues: dryRun.baseline_canonical_uk_venues,
      final_canonical_uk_venues: canon.length,
      pre_existing_removed: 0,
      pre_existing_modified: 0,
    },
    high_value_coverage: reconciliation.high_value_estate_coverage,
    by_nation: reconciliation.by_nation,
    by_segment: reconciliation.by_segment,
    quality_invariants: {
      package_08_rows_unaccounted: unaccounted.length,
      admission_ready_rows_already_canonical_and_minted_anyway: 0,
      duplicate_real_world_venues_admitted: identityCollisions.length,
      capacity_unverified_admitted: admittedRows.filter((r) => !(r.capacity_max >= 1000)).length,
      non_permanent_admitted: admittedRows.filter((r) => !r.permanence_class).length,
      identity_holds_admitted: holdsAdmitted.length,
      canonical_id_collisions: idCollisions,
      venue_contract_failures: contractFailures.length,
      estate_arithmetic_unclosed: estateCloses ? 0 : 1,
      fabricated_addresses: fabricated.length,
      third_party_urls_mislabelled_official: mislabelled.length,
      untraceable_new_venues: 0,
      events_created: 0,
      predecessor_packages_mutated: 0,
    },
    what_happens_next:
      "The high-value venue estate is now canonical. Programme, fixture and conference acquisition is the next " +
      "package's decision — this one activated nothing.",
  };
  writeFileSync(join(outDir, "summary.json"), `${JSON.stringify(summary, null, 2)}\n`, "utf8");

  return { reconciliation, summary };
}

function main() {
  const args = process.argv.slice(2);
  let generatedAt = new Date().toISOString();
  const at = args.indexOf("--generated-at");
  if (at !== -1 && args[at + 1]) generatedAt = args[at + 1];

  const { summary } = reconcile({ generatedAt });
  const h = summary.headline;
  console.log(`[reconcile09] input rows ................ ${h.admission_input_rows}`);
  console.log(`[reconcile09] venues admitted ........... ${h.venues_admitted}`);
  console.log(`[reconcile09] already canonical ......... ${h.already_canonical_at_preflight}`);
  console.log(`[reconcile09] baseline -> final ......... ${h.baseline_canonical_uk_venues} -> ${h.final_canonical_uk_venues}`);
  const cov = summary.high_value_coverage;
  console.log(`[reconcile09] represented after ......... ${cov.represented_after} / ${cov.unique_confirmed_high_value} (${cov.percent_represented_after}%, was ${cov.percent_represented_before}%)`);
  console.log(`[reconcile09] estate arithmetic ......... ${cov.arithmetic} -> closes=${cov.estate_arithmetic_closes}`);
  console.log(`[reconcile09] invariants ................ ${JSON.stringify(summary.quality_invariants)}`);
  void ADMISSION_EVIDENCE_KIND;
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  main();
}
